apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jupyterhub-staging
resources:
  - ./namespace.yaml
  - ../base
namespace: jh-staging-system
patches:
  - path: jupyterhub-values.yaml
    target:
      kind: HelmRelease
