apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jupyterhub
spec:
  chart:
    spec:
      chart: jupyterhub
      sourceRef:
        kind: HelmRepository
        name: jupyterhub
      version: "3.0.0-beta.3.git.6268.h16086582"
  interval: 5m0s
  releaseName: jupyterhub
  values:
    hub:
      image:
        name: ghcr.io/cta-epfl/k8s-hub
        tag: v0.0.6
      loadRoles:
        user:
          scopes:
            - self
        downloadservice:
          users:
            - admin
          scopes:
            - "access:services!service=downloadservice"
      services:
        downloadservice:
          url: http://hub:5000
          command:
            - /usr/local/bin/python3
            - /downloadservice/downloadservice/cli.py
      networkPolicy:
        allowedIngressPorts:
          - 5000
        ingress:
          - ports:
              - port: 5000
            from:
              - podSelector:
                  matchLabels:
                    hub.jupyter.org/network-access-hub: "true"
      service:
        extraPorts:
          - port: 5000
            targetPort: 5000
            name: downloadservice
    prePuller:
      hook:
        enabled: false
